language: python
sudo: false
dist: xenial
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all

stages:
  - check
  - test
  - deploy

jobs:
  include:
    # Stage Check
    - stage: check
      python: '2.7'
      env:
        - TOXENV=py27-check
    - stage: check
      python: '3.7'
      env:
        - TOXENV=py37-check
    # Stage test
    - stage: test
      python: '2.7'
      env:
        - TOXENV=py27-test,py27-sphinx1.3,py27-sphinx1.4,py27-sphinx1.5,py27-sphinx1.6,py27-sphinxlatest
    - stage: test
      python: '3.7'
      env:
        - TOXENV=py37-test,py37-sphinx1.3,py37-sphinx1.4,py37-sphinx1.5,py37-sphinx1.6,py37-sphinxlatest,py37-codecov
    # Stage deploy
    - stage: deploy
      python: 3.7
      env:
        - TOXENV=py37-test,py37-sphinxlatest,py37-codecov
      deploy:
        # production pypi
        - provider: pypi
          distributions: sdist bdist_wheel
          user: Letme
          password:
              secure: "ZhogUet19V4cfbIXmlEepK5PemHiIl6UQwjleCEh9sTfmxgYiAMsDHIvSHSDArXPiFJ9BZlBX4vBmhGEyrUp58I+Rn4V7nm3Ml+KB0pQTvoUruNM2uA7fmBT76i2OGSuDl1pc3Ap2ajTNWDYltBJN7o0/l9QsgC65oe76Uvj4kPJCcfp2xT3e7uw/bt1JLegQGYChOUG7uz9HnsbwZ9eejx5Ogxrmeb42/5cFAokkC4eUs9rYuaRuNLzfNzStBE1QWRXQRqDgfw5FwFnkXYrNwetqjcnHWa5+7ljyKg36jcWDKDeHWXdThGJm8pLVaKthMv/+GgPoUn65Y+aw89bXTkdfCzWaye9GEo2wkRi7nziRFNsm5rNA2eKHjCcmtk8uPwszyMQo9VQ2aeeQ8cnAK6NBR2U6OytAyIb9ptXS/MHECAB0Elo71QE9gyFesWGjVOLbSUy91ZA0pifZlFMmBGd60Bt7MlNUGpFpuRq7Rr8n11Tdr6BIycKbMYhIahwQeCq47pgv9X/RQRbfpp9GpRPY+/IT24mYDIhzKzWSBRXWGPEY/fBIwG7AM88COsNXejmn8EgwYQCjSdLxLxsVv5LRrD4B6dOLb920MUR+sMNWCw2AmPNckV6LIgw5/r44yOOSYGva2cgJk66BQ4DaFrJMADTEyO/NSg6jhZocD8="
          on:
            branch: master
            python: 3.7
            tags: true
        # publish example: build by tox, published to pages
        - provider: pages
          skip_cleanup: true
          local_dir: example/_build/html/
          github_token: $GITHUB_TOKEN
          on:
            branch: master
            python: 3.7

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - pip install tox
  - pip install coverage
  - pip install python-decouple
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

script:
  - tox -v

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

notifications:
  email:
    on_success: never
    on_failure: always

# Deploy: disable jekyll in order to publish subfolders with leading underscores as well to pages
before_deploy:
  - mkdir -p example/_build/html/
  - touch example/_build/html/.nojekyll

